# Jekyll Configuration

url: http://localhost:4000 #XXX
title: Ificate
description: Stuff.
author: Everett Carney Wilson
email: negativek@ificate.net
google_id: negativek
#analytics_id: UA-000-000 #Google Analytics ID : UA-xxx-xxx  

auto: false
lsi: false
pygments: false
server_port: 4000
markdown: maruku

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex
